[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2c3e50"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#c3cfe2"
textColor = "#2c3e50"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = true
enforceSerializableSessionState = false
