[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#8B5CF6"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#F3E8FF"
textColor = "#4C1D95"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = true
enforceSerializableSessionState = false
