[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#42A5F5"
backgroundColor = "#E3F2FD"
secondaryBackgroundColor = "#B3E5FC"
textColor = "#1565C0"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = true
enforceSerializableSessionState = false
