[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1e3a8a"
backgroundColor = "#ddd6fe"
secondaryBackgroundColor = "#c4b5fd"
textColor = "#1e3a8a"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = true
enforceSerializableSessionState = false