[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#f8f9ff"
secondaryBackgroundColor = "#e8f4fd"
textColor = "#667eea"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = true
enforceSerializableSessionState = false
