[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#A0C4FF"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#343A40"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = true
enforceSerializableSessionState = false