[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0984e3"
backgroundColor = "#74b9ff"
secondaryBackgroundColor = "#0984e3"
textColor = "#0984e3"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = true
enforceSerializableSessionState = false
