[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#495057"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#e9ecef"
textColor = "#495057"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = true
enforceSerializableSessionState = false