[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#9c27b0"
backgroundColor = "#e1bee7"
secondaryBackgroundColor = "#ce93d8"
textColor = "#9c27b0"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = true
enforceSerializableSessionState = false
