[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2196F3"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#E3F2FD"
textColor = "#1A237E"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = true
enforceSerializableSessionState = false
